[package]
name = "slim"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "cargo-slim"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
walkdir = "2.5.0"
